'use client';
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai';
import Image from "next/image";
import jaysax from '../../public/jaysax.jpg';

import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jean St. Cloud's Portfolio</title>
        <meta name="description" content='Generated by Jean'/> 
        <link rel='icon' href="./favicon.ico"/>
       </Head>
    <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='min-h-screen dark:bg-gray-900'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons text-blue-200'>Developed by WyattChase</h1>
          <ul className='flex items-center'>
            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-black dark:text-white'/></li>
            <l1><a className='bg-gradient-to-r from-cyan-500 to-purple-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></l1>
          </ul>
        </nav>
        <div className='text-center p-10 py-10'>
          <h2 className='text-5xl py-3 text-teal-600 font-medium'>Jean St. Cloud</h2>
          <h3 className='text 2xl- py-2 text-gray-300'>Software Developer and Game Programmer/Designer</h3>
          <p className='text-md py-4 leading-8 text-gray-800'>Yada yada join me down below</p>
        </div>
        <div className='text-5xl justify-center flex gap-16 py-3 text-gray-600'>
          <AiFillLinkedin />
          <AiFillGithub />
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
          <Image src={jaysax} layout="fill" objectFit="cover"/>
        </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl py-1'>Services I offer</h3>
          <p className='text-md py-4 leading-8 text-gray-800'>FreeLance Games Music </p>
        </div>
        <div>
          <div>
            <Image src/>
          </div>
        </div>
      </section>
      {/*  */}
    </main>
    </div>
  )
}
